### ISSUE TITLE
Invalid search result range Error 

### ISSUE THREAD

**Issue by bhappyz** [privatenumber/snap-tweet#17] opened 2021-11-18 09:57 UTC
On some tweets reply button is not showing by default. This breaks the code and gives an error Invalid search result range

**Comment by privatenumber** [comment] 2022-01-06 13:22
Do you have an example to demonstrate this bug?

**Comment by privatenumber** [comment] 2022-02-16 21:10
Closing due to lack of reproduction. Happy to reopen once provided.

**Closed by privatenumber** 2022-02-16 21:10 UTC
